# Default values for mychart.
replicaCount: 1

image:
  repository: korcomptenz.jfrog.io/docker-trial/exposures/repository
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: jfrog-mysecret1

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

deployment:
  name: pradeep-dep
  namespace: jfrog

container:
  name: mynew-container
  port: 80

podLabels:
  app: myapp3
