name: Docker Build, Push to JFrog, and Deploy to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to JFrog
      uses: docker/login-action@v2
      with:
        registry: korcomptenz.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./Applicationcode1
        file: ./Applicationcode1/Dockerfile
        push: true
        tags: |
           korcomptenz.jfrog.io/docker-trial/exposures/repository:1.0.0
  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.4.0
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Azure login and AKS credentials setup
      run: |
        az login --service-principal --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} --tenant 16a5cb4e-4988-44af-a98d-cddb642c8fe0
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

    - name: Login to JFrog
      uses: docker/login-action@v2
      with:
        registry: korcomptenz.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}
 
    - name: Deploy to AKS
      run: |
        helm upgrade --install helmrelease ./mychart \
          --namespace jfrog \
          --set image.repository=korcomptenz.jfrog.io/docker-trial/exposures/repository \
          --set image.tag=1.0.0 \
              
           
