name: Docker Build, Push to JFrog, and Deploy to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to JFrog
      uses: docker/login-action@v2
      with:
        registry: korcomptenz.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./Applicationcode1
        file: ./Applicationcode1/Dockerfile
        push: true
        tags: |
           korcomptenz.jfrog.io/docker-trial/exposures/repository:1.0.0
